Repository DSM-PICK/PiCK2024_FRONT_V2, pull requests merged in 2024-06, with the labels that each got.

#19 add : api세팅
  package.json
  src/apis/.gitkeep
  src/apis/index.ts
  src/index.tsx
  src/styles/theme.ts
  src/utils/auth.ts
  yarn.lock
Labels: api연동

#16 Main page
  src/assets/svg/academicCalendar.svg
  src/assets/svg/afterSchool.svg
  src/assets/svg/changeTeacher.svg
  src/assets/svg/classAttendance.svg
  src/assets/svg/classroomMovementImg.svg
  src/assets/svg/clubManagement.svg
  src/assets/svg/goingOutList.svg
  src/assets/svg/mainLogo.svg
  src/assets/svg/notification.svg
  src/assets/svg/outingAllow.svg
  src/assets/svg/outingHistory.svg
  src/assets/svg/timetableChange.svg
  src/assets/svg/weekendMeals.svg
  src/components/mainRouterButton/index.tsx
  src/components/mainRouterButton/style.ts
  src/index.tsx
  src/pages/Main/index.tsx
  src/pages/Main/style.ts
Labels: 퍼블리싱

#23 add : header 기능 및 react-query tanstack 변경
  .gitignore
  package.json
  src/App.tsx
  src/apis/application/index.ts
  src/apis/login/index.ts
  src/apis/meal/index.ts
  src/apis/self-study/index.ts
  src/apis/type.ts
  src/assets/svg/close.svg
  src/components/StudentsState/index.tsx
  src/components/StudentsState/style.ts
  src/components/alarm/style.ts
  src/components/header/index.tsx
  src/components/header/style.ts
  src/components/helpmenu/content.tsx
  src/components/helpmenu/index.tsx
  src/components/helpmenu/style.ts
  src/components/meal/index.tsx
  src/components/meal/style.ts
  src/components/menu/index.tsx
  src/components/menu/style.ts
  src/components/modal/index.tsx
  src/components/modal/style.ts
  src/components/selfStudyTeacher/index.tsx
  src/components/selfStudyTeacher/style.ts
  src/index.tsx
  src/pages/login/index.tsx
  src/styles/theme.ts
  src/utils/date.ts
  yarn.lock
Labels: 퍼블리싱, 기능개발, api연동

#24 Dropdown component
  src/assets/svg/dropdownImg.svg
  src/components/dropdown/index.tsx
  src/components/dropdown/style.ts
Labels: 기능개발

#32 add : icon svg
  src/assets/svg/home.svg
  src/assets/svg/next.svg
Labels: 퍼블리싱

#31 add : searchInput
  src/assets/svg/search.svg
  src/components/Button/bottom.tsx
  src/components/Button/style.ts
  src/components/input/search.tsx
  src/components/input/style.ts
Labels: 퍼블리싱, 기능개발

#33 add : notice
  src/App.tsx
  src/apis/notice/index.ts
  src/apis/type.ts
  src/components/mainRouterButton/index.tsx
  src/components/noticeList/index.tsx
  src/components/noticeList/style.ts
  src/pages/notice/detail/index.tsx
  src/pages/notice/index.tsx
  src/pages/notice/style.ts
  src/pages/notice/write/index.tsx
Labels: 퍼블리싱, 기능개발, api연동

#37 fix : 공지 성공 시 페이지 전환
  src/pages/notice/write/index.tsx
Labels: 기능개발
